spring:
  application:
    name: pixogram-front
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

zuul:
  routes:
    token:
      serviceId: images
      path: /images/**
      stripPrefix: false


ribbon:
  eureka:
    enabled: true

