spring:
  application:
    name: pixogram-front
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081
  ssl:
    key-store-type: PKCS12
    key-store: classpath:cristi.p12
    # The path to the keystore containing the certificate
    # The password used to generate the certificate
    key-store-password: cristi
    # The alias mapped to the certificate
    key-alias: bonitos
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

zuul:
  routes:
    token:
      serviceId: images
      path: /images/**
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false



ribbon:
  eureka:
    enabled: true



